#!/usr/bin/env node
/**
 * Validates every test case document and rebuilds test-cases/index.md.
 *
 * The index doubles as the test case ID registry: it reports the next free ID
 * per project so IDs never collide.
 *
 * Usage:
 *   npm run index     # validate and rewrite the index
 *   npm run check     # validate only, non-zero exit on any error
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { ROOT, loadConfig, listMarkdown, parseFrontmatter, parseTestCases, relative, TC_ID_PATTERN, log } from './lib.mjs';

const CHECK_ONLY = process.argv.includes('--check');
const CROSS_PROJECT = { key: 'cross-project', name: 'Cross-Project E2E', idPrefix: 'E2E', testCasePath: 'test-cases/cross-project' };
const STATUSES = ['draft', 'reviewed', 'approved', 'superseded'];
const COVERAGE_STATUSES = ['READY FOR TESTING', 'READY WITH MINOR GAPS', 'REQUIRES CLARIFICATION'];
const REQUIRED = ['project', 'ticket', 'title', 'created', 'status'];

function collect(config) {
  const scopes = [...config.projects, CROSS_PROJECT];
  const documents = [];
  const errors = [];

  for (const scope of scopes) {
    for (const file of listMarkdown(path.join(ROOT, scope.testCasePath))) {
      const rel = relative(file);
      const { data, body } = parseFrontmatter(readFileSync(file, 'utf8'));

      for (const key of REQUIRED) {
        if (!data[key]) errors.push(`${rel}: missing required front matter field \`${key}\``);
      }
      if (data.project && data.project !== scope.key) {
        errors.push(`${rel}: front matter says project \`${data.project}\` but the file lives under \`${scope.testCasePath}\``);
      }
      if (data.status && !STATUSES.includes(data.status)) {
        errors.push(`${rel}: status \`${data.status}\` is not one of ${STATUSES.join(', ')}`);
      }
      if (data.coverage_status && !COVERAGE_STATUSES.includes(data.coverage_status)) {
        errors.push(`${rel}: coverage_status \`${data.coverage_status}\` is not one of ${COVERAGE_STATUSES.join(' | ')}`);
      }

      const cases = parseTestCases(body);
      if (cases.length === 0) errors.push(`${rel}: no \`## <ID> — <Title>\` test case headings found`);

      for (const testCase of cases) {
        if (!TC_ID_PATTERN.test(testCase.id)) {
          errors.push(`${rel}: malformed test case id \`${testCase.id}\``);
        } else if (!testCase.id.startsWith(`${scope.idPrefix}-TC-`)) {
          errors.push(`${rel}: test case \`${testCase.id}\` should use the \`${scope.idPrefix}-TC-\` prefix`);
        }
        if (!testCase.priority) errors.push(`${rel}: ${testCase.id} is missing **Priority:**`);
        if (!testCase.steps) errors.push(`${rel}: ${testCase.id} is missing **Steps:**`);
        if (!testCase.expected) errors.push(`${rel}: ${testCase.id} is missing **Expected Result:**`);
      }

      const declared = data.test_case_ids || [];
      const actual = cases.map((testCase) => testCase.id);
      const undeclared = actual.filter((id) => !declared.includes(id));
      if (declared.length > 0 && undeclared.length > 0) {
        errors.push(`${rel}: front matter test_case_ids is missing ${undeclared.join(', ')}`);
      }

      documents.push({ scope, file: rel, data, cases });
    }
  }

  const owners = new Map();
  for (const doc of documents) {
    for (const testCase of doc.cases) {
      if (owners.has(testCase.id)) {
        errors.push(`Duplicate test case id \`${testCase.id}\` in ${owners.get(testCase.id)} and ${doc.file}`);
      } else {
        owners.set(testCase.id, doc.file);
      }
    }
  }

  return { scopes, documents, errors };
}

function nextId(prefix, documents) {
  let max = 0;
  for (const doc of documents) {
    for (const testCase of doc.cases) {
      const match = new RegExp(`^${prefix}-TC-(\\d+)$`).exec(testCase.id);
      if (match) max = Math.max(max, Number(match[1]));
    }
  }
  return `${prefix}-TC-${String(max + 1).padStart(3, '0')}`;
}

function render(scopes, documents) {
  const lines = [];
  lines.push('# Test Case Index');
  lines.push('');
  lines.push('> Generated by `npm run index`. Do not edit by hand — your changes will be overwritten.');
  lines.push('');

  lines.push('## Next Free Test Case ID');
  lines.push('');
  lines.push('Use these when writing a new document. Re-run `npm run index` afterwards.');
  lines.push('');
  lines.push('| Scope | Next ID | Documents | Test Cases |');
  lines.push('| --- | --- | --- | --- |');
  for (const scope of scopes) {
    const scoped = documents.filter((doc) => doc.scope.key === scope.key);
    const caseCount = scoped.reduce((sum, doc) => sum + doc.cases.length, 0);
    lines.push(`| ${scope.name} | \`${nextId(scope.idPrefix, documents)}\` | ${scoped.length} | ${caseCount} |`);
  }
  lines.push('');

  for (const scope of scopes) {
    const scoped = documents
      .filter((doc) => doc.scope.key === scope.key)
      .sort((a, b) => String(b.data.created).localeCompare(String(a.data.created)));

    lines.push(`## ${scope.name}`);
    lines.push('');
    if (scoped.length === 0) {
      lines.push('_No test case documents yet._');
      lines.push('');
      continue;
    }
    lines.push('| Created | Ticket | Title | Cases | Status | Coverage | Against Commit | Affects | File |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
    for (const doc of scoped) {
      const affects = (doc.data.affects || []).join(', ') || '—';
      const commit = doc.data.source_commit ? `\`${doc.data.source_commit}\`` : '—';
      lines.push(
        `| ${doc.data.created || '—'} | ${doc.data.ticket || '—'} | ${doc.data.title || '—'} | ${doc.cases.length} | ${doc.data.status || '—'} | ${doc.data.coverage_status || '—'} | ${commit} | ${affects} | [${path.basename(doc.file)}](${path.relative('test-cases', doc.file).split(path.sep).join('/')}) |`
      );
    }
    lines.push('');
  }

  const total = documents.reduce((sum, doc) => sum + doc.cases.length, 0);
  lines.push('---');
  lines.push('');
  lines.push(`**Total:** ${documents.length} documents, ${total} test cases.`);
  lines.push('');
  return lines.join('\n');
}

function main() {
  const config = loadConfig();
  const { scopes, documents, errors } = collect(config);

  if (errors.length > 0) {
    log.info('Validation errors:\n');
    for (const error of errors) log.fail(error);
    log.info('');
  }

  if (CHECK_ONLY) {
    if (errors.length > 0) process.exit(1);
    log.ok(`${documents.length} documents valid`);
    return;
  }

  writeFileSync(path.join(ROOT, 'test-cases', 'index.md'), render(scopes, documents));
  log.info(`Wrote test-cases/index.md — ${documents.length} documents, ${documents.reduce((sum, doc) => sum + doc.cases.length, 0)} test cases`);
  for (const scope of scopes) {
    log.info(`  next ${scope.name}: ${nextId(scope.idPrefix, documents)}`);
  }
  if (errors.length > 0) process.exit(1);
}

main();
