#!/usr/bin/env node
/**
 * Records the outcome of a test execution.
 *
 * Today runs are executed manually and logged with this script. When execution
 * is automated later, the runner writes the same records and nothing about the
 * history format has to change.
 *
 * Usage:
 *   npm run log:run -- --ticket CU-1234 --project rms --env staging \
 *     --case RMS-TC-001=pass \
 *     --case RMS-TC-002=fail:"Duplicate error toast shown" \
 *     --notes "Retested after hotfix"
 *
 *   npm run log:run -- --ticket CU-1234 --project rms --from test-cases/rms/CU-1234.md --result pass
 *
 * Results: pass | fail | blocked | skipped
 */
import { readFileSync, writeFileSync, appendFileSync, existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { ROOT, parseFrontmatter, parseTestCases, today, log } from './lib.mjs';

const RESULTS = ['pass', 'fail', 'blocked', 'skipped'];
const RUNS_DIR = path.join(ROOT, 'test-runs');
const JSONL = path.join(RUNS_DIR, 'runs.jsonl');

function parseArgs(argv) {
  const options = { cases: [] };
  for (let i = 0; i < argv.length; i++) {
    if (!argv[i].startsWith('--')) continue;
    const key = argv[i].slice(2);
    const value = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : 'true';
    if (key === 'case') options.cases.push(value);
    else options[key] = value;
  }
  return options;
}

function parseCase(spec) {
  const eq = spec.indexOf('=');
  if (eq === -1) throw new Error(`--case expects ID=result, got "${spec}"`);
  const id = spec.slice(0, eq).trim();
  const rest = spec.slice(eq + 1).trim();
  const colon = rest.indexOf(':');
  const result = (colon === -1 ? rest : rest.slice(0, colon)).trim().toLowerCase();
  const note = colon === -1 ? '' : rest.slice(colon + 1).trim().replace(/^"|"$/g, '');
  if (!RESULTS.includes(result)) throw new Error(`Unknown result "${result}" for ${id}. Use: ${RESULTS.join(', ')}`);
  return { id, result, note };
}

function renderRun(run) {
  const lines = [];
  lines.push(`## Run ${run.runId} — ${run.date}`);
  lines.push('');
  lines.push(`- **Tester:** ${run.tester}`);
  lines.push(`- **Project:** ${run.project}`);
  lines.push(`- **Environment:** ${run.environment}`);
  if (run.build) lines.push(`- **Build / Commit:** \`${run.build}\``);
  lines.push(`- **Executed by:** ${run.executedBy}`);
  lines.push(`- **Summary:** ${run.summary.pass} passed · ${run.summary.fail} failed · ${run.summary.blocked} blocked · ${run.summary.skipped} skipped`);
  lines.push('');
  lines.push('| Test Case | Result | Note |');
  lines.push('| --- | --- | --- |');
  for (const item of run.cases) {
    lines.push(`| ${item.id} | ${item.result.toUpperCase()} | ${item.note || '—'} |`);
  }
  lines.push('');
  if (run.notes) {
    lines.push(`**Notes:** ${run.notes}`);
    lines.push('');
  }
  return lines.join('\n');
}

function rebuildHistory() {
  if (!existsSync(JSONL)) return;
  const runs = readFileSync(JSONL, 'utf8')
    .split('\n')
    .filter(Boolean)
    .map((line) => JSON.parse(line))
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp));

  const lines = [];
  lines.push('# Test Run History');
  lines.push('');
  lines.push('> Generated by `npm run log:run`. Do not edit by hand.');
  lines.push('');
  lines.push('| Date | Ticket | Project | Env | Pass | Fail | Blocked | Skipped | Tester | Detail |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const run of runs) {
    lines.push(
      `| ${run.date} | ${run.ticket} | ${run.project} | ${run.environment} | ${run.summary.pass} | ${run.summary.fail} | ${run.summary.blocked} | ${run.summary.skipped} | ${run.tester} | [${run.ticket}.md](${run.ticket}.md) |`
    );
  }
  lines.push('');

  const failing = new Map();
  for (const run of runs) {
    for (const item of run.cases) {
      if (item.result === 'fail' && !failing.has(item.id)) {
        failing.set(item.id, { ...item, date: run.date, ticket: run.ticket });
      }
    }
  }
  lines.push('## Most Recent Failures');
  lines.push('');
  if (failing.size === 0) {
    lines.push('_No recorded failures._');
  } else {
    lines.push('| Test Case | Last Failed | Ticket | Note |');
    lines.push('| --- | --- | --- | --- |');
    for (const item of failing.values()) {
      lines.push(`| ${item.id} | ${item.date} | ${item.ticket} | ${item.note || '—'} |`);
    }
  }
  lines.push('');
  writeFileSync(path.join(RUNS_DIR, 'HISTORY.md'), lines.join('\n'));
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  if (!options.ticket || !options.project) {
    log.fail('Required: --ticket <id> --project <key>');
    process.exit(1);
  }

  let cases = options.cases.map(parseCase);

  if (options.from) {
    const defaultResult = (options.result || 'pass').toLowerCase();
    if (!RESULTS.includes(defaultResult)) {
      log.fail(`--result must be one of ${RESULTS.join(', ')}`);
      process.exit(1);
    }
    const { body } = parseFrontmatter(readFileSync(path.resolve(ROOT, options.from), 'utf8'));
    const explicit = new Set(cases.map((item) => item.id));
    for (const testCase of parseTestCases(body)) {
      if (!explicit.has(testCase.id)) cases.push({ id: testCase.id, result: defaultResult, note: '' });
    }
  }

  if (cases.length === 0) {
    log.fail('Nothing to log. Pass --case ID=result and/or --from <test-case-doc>.');
    process.exit(1);
  }

  cases = cases.sort((a, b) => a.id.localeCompare(b.id, undefined, { numeric: true }));
  const summary = Object.fromEntries(RESULTS.map((result) => [result, cases.filter((item) => item.result === result).length]));

  mkdirSync(RUNS_DIR, { recursive: true });
  const ticketFile = path.join(RUNS_DIR, `${options.ticket}.md`);
  const existing = existsSync(ticketFile) ? readFileSync(ticketFile, 'utf8') : '';
  const runId = (existing.match(/^## Run /gm) || []).length + 1;

  const run = {
    runId,
    timestamp: new Date().toISOString(),
    date: today(),
    ticket: options.ticket,
    project: options.project,
    environment: options.environment || options.env || 'unspecified',
    build: options.build || '',
    tester: options.tester || 'unspecified',
    executedBy: options.automated === 'true' ? 'automation' : 'manual',
    notes: options.notes || '',
    summary,
    cases,
  };

  const header = existing || `# Test Runs — ${options.ticket}\n\nExecution history for [test cases](../test-cases/${options.project}/${options.ticket}.md).\n\n`;
  writeFileSync(ticketFile, `${header}${header.endsWith('\n\n') ? '' : '\n'}${renderRun(run)}`);
  appendFileSync(JSONL, JSON.stringify(run) + '\n');
  rebuildHistory();

  log.ok(`Run ${runId} logged to test-runs/${options.ticket}.md`);
  log.info(`  ${summary.pass} passed · ${summary.fail} failed · ${summary.blocked} blocked · ${summary.skipped} skipped`);
}

main();
