#!/usr/bin/env node
/**
 * Refreshes the read-only mirrors of the source project repositories and writes
 * a state snapshot for each one under project-state/.
 *
 * The mirrors live in .cache/repos/<key>.git and are the ONLY place the agent
 * reads source code from. They are blobless mirror clones with the push URL
 * disabled, so nothing in this workspace can write to the real repositories.
 *
 * Usage:
 *   npm run sync                 # all configured projects
 *   npm run sync -- rms wms      # only the given projects
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { ROOT, loadConfig, isConfigured, log } from './lib.mjs';

const RS = '\x1e';
const US = '\x1f';
const NO_PUSH = 'no-push://read-only-mirror';

function git(args, options = {}) {
  return execFileSync('git', args, { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, ...options }).trim();
}

function gitIn(dir, args) {
  return git(['-C', dir, ...args]);
}

function tryGitIn(dir, args) {
  try {
    return gitIn(dir, args);
  } catch {
    return null;
  }
}

function ensureMirror(project, mirrorDir) {
  if (existsSync(mirrorDir)) {
    log.info(`  fetching ${project.key} ...`);
    gitIn(mirrorDir, ['fetch', '--prune', '--quiet']);
  } else {
    log.info(`  cloning ${project.key} (blobless mirror, first run may take a while) ...`);
    mkdirSync(path.dirname(mirrorDir), { recursive: true });
    git(['clone', '--mirror', '--filter=blob:none', '--quiet', project.repo, mirrorDir]);
  }
  // Defence in depth: make an accidental push physically impossible.
  gitIn(mirrorDir, ['config', 'remote.origin.pushurl', NO_PUSH]);
}

function resolveBranch(mirrorDir, preferred) {
  if (preferred && tryGitIn(mirrorDir, ['rev-parse', '--verify', '--quiet', `${preferred}^{commit}`])) {
    return preferred;
  }
  const head = tryGitIn(mirrorDir, ['symbolic-ref', '--short', 'HEAD']);
  if (head && tryGitIn(mirrorDir, ['rev-parse', '--verify', '--quiet', `${head}^{commit}`])) return head;
  for (const fallback of ['main', 'master', 'develop']) {
    if (tryGitIn(mirrorDir, ['rev-parse', '--verify', '--quiet', `${fallback}^{commit}`])) return fallback;
  }
  return null;
}

function readCommits(mirrorDir, branch, depth) {
  const format = `${RS}%H${US}%h${US}%aI${US}%an${US}%s${US}%P`;
  const raw = gitIn(mirrorDir, ['log', `-n${depth}`, `--format=${format}`, '--name-status', branch]);

  return raw
    .split(RS)
    .filter((chunk) => chunk.trim())
    .map((chunk) => {
      const [header, ...rest] = chunk.split('\n');
      const [sha, short, date, author, subject, parents] = header.split(US);
      const files = rest
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
          const [status, ...paths] = line.split('\t');
          return { status, path: paths[paths.length - 1] };
        });
      return {
        sha,
        short,
        date,
        author,
        subject,
        isMerge: (parents || '').trim().split(/\s+/).filter(Boolean).length > 1,
        files,
      };
    });
}

function readHotspots(mirrorDir, branch, days) {
  const raw = gitIn(mirrorDir, ['log', `--since=${days} days ago`, '--format=', '--name-only', branch]);
  const counts = new Map();
  for (const line of raw.split('\n')) {
    const file = line.trim();
    if (!file) continue;
    counts.set(file, (counts.get(file) || 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 20)
    .map(([file, changes]) => ({ file, changes }));
}

function readBranches(mirrorDir) {
  const raw = tryGitIn(mirrorDir, [
    'for-each-ref',
    '--sort=-committerdate',
    '--count=15',
    '--format=%(refname:short)' + US + '%(committerdate:iso-strict)' + US + '%(authorname)',
    'refs/heads',
  ]);
  if (!raw) return [];
  return raw
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const [name, date, author] = line.split(US);
      return { name, lastCommitDate: date, lastCommitAuthor: author };
    });
}

function renderChangelog(project, state) {
  const lines = [];
  lines.push(`# ${project.name} — Recent Changes`);
  lines.push('');
  lines.push('> Generated by `npm run sync`. Do not edit by hand — your changes will be overwritten.');
  lines.push('');

  if (!state.configured) {
    lines.push(`**Status:** not configured. Set \`repo\` for \`${project.key}\` in \`config/projects.json\`, then run \`npm run sync\`.`);
    lines.push('');
    return lines.join('\n');
  }

  lines.push(`- **Repository:** \`${state.repo}\``);
  lines.push(`- **Branch:** \`${state.branch}\``);
  lines.push(`- **HEAD:** \`${state.head.short}\` — ${state.head.subject}`);
  lines.push(`- **HEAD date:** ${state.head.date}`);
  lines.push(`- **Synced at:** ${state.syncedAt}`);
  lines.push('');

  lines.push('## Active Branches');
  lines.push('');
  if (state.branches.length === 0) {
    lines.push('_None found._');
  } else {
    lines.push('| Branch | Last Commit | Author |');
    lines.push('| --- | --- | --- |');
    for (const branch of state.branches) {
      lines.push(`| \`${branch.name}\` | ${branch.lastCommitDate.slice(0, 10)} | ${branch.lastCommitAuthor} |`);
    }
  }
  lines.push('');

  lines.push(`## Change Hotspots (last ${state.hotspotWindowDays} days)`);
  lines.push('');
  lines.push('Files touched most often. These are the highest-value regression targets.');
  lines.push('');
  if (state.hotspots.length === 0) {
    lines.push('_No commits in this window._');
  } else {
    lines.push('| Changes | File |');
    lines.push('| --- | --- |');
    for (const hotspot of state.hotspots) {
      lines.push(`| ${hotspot.changes} | \`${hotspot.file}\` |`);
    }
  }
  lines.push('');

  lines.push(`## Last ${state.commits.length} Commits`);
  lines.push('');
  for (const commit of state.commits) {
    lines.push(`### \`${commit.short}\` — ${commit.subject}`);
    lines.push('');
    lines.push(`${commit.author} · ${commit.date}${commit.isMerge ? ' · merge commit' : ''}`);
    lines.push('');
    if (commit.files.length === 0) {
      lines.push('_No file list (merge commit)._');
    } else {
      for (const file of commit.files) {
        lines.push(`- \`${file.status}\` \`${file.path}\``);
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## How to inspect any of these commits');
  lines.push('');
  lines.push('```bash');
  lines.push(`git -C ${state.mirrorDir} show <sha>`);
  lines.push(`git -C ${state.mirrorDir} show <sha> --stat`);
  lines.push(`git -C ${state.mirrorDir} show <sha>:<path>`);
  lines.push(`git -C ${state.mirrorDir} diff <old-sha>..<new-sha> -- <path>`);
  lines.push('```');
  lines.push('');
  return lines.join('\n');
}

function renderSummary(states) {
  const lines = [];
  lines.push('# Project State Summary');
  lines.push('');
  lines.push('> Generated by `npm run sync`. Do not edit by hand.');
  lines.push('');
  lines.push('| Project | Branch | HEAD | Last Commit | Synced |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const { project, state } of states) {
    if (!state.configured) {
      lines.push(`| ${project.name} | — | — | _not configured_ | — |`);
      continue;
    }
    lines.push(
      `| ${project.name} | \`${state.branch}\` | \`${state.head.short}\` | ${state.head.date.slice(0, 10)} — ${state.head.subject} | ${state.syncedAt.slice(0, 10)} |`
    );
  }
  lines.push('');
  return lines.join('\n');
}

function main() {
  const config = loadConfig();
  const filter = process.argv.slice(2).filter((arg) => !arg.startsWith('-'));
  const selected = filter.length
    ? config.projects.filter((project) => filter.includes(project.key))
    : config.projects;

  if (selected.length === 0) {
    log.fail(`No matching projects. Known keys: ${config.projects.map((p) => p.key).join(', ')}`);
    process.exit(1);
  }

  log.info('Syncing source project mirrors\n');
  const states = [];

  for (const project of selected) {
    const statePath = path.join(ROOT, project.statePath);
    mkdirSync(statePath, { recursive: true });

    if (!isConfigured(project)) {
      log.skip(`${project.key} — repo not configured in config/projects.json`);
      const state = { project: project.key, configured: false, syncedAt: new Date().toISOString() };
      writeFileSync(path.join(statePath, 'state.json'), JSON.stringify(state, null, 2) + '\n');
      writeFileSync(path.join(statePath, 'recent-changes.md'), renderChangelog(project, state));
      states.push({ project, state });
      continue;
    }

    const mirrorDir = path.join(ROOT, config.cacheDir, `${project.key}.git`);
    try {
      ensureMirror(project, mirrorDir);
    } catch (error) {
      log.fail(`${project.key} — ${error.message.split('\n')[0]}`);
      states.push({ project, state: { project: project.key, configured: false, error: error.message } });
      continue;
    }

    const branch = resolveBranch(mirrorDir, project.defaultBranch);
    if (!branch) {
      log.fail(`${project.key} — could not resolve a branch to read`);
      continue;
    }

    const commits = readCommits(mirrorDir, branch, config.historyDepth ?? 40);
    const state = {
      project: project.key,
      name: project.name,
      configured: true,
      repo: project.repo,
      branch,
      mirrorDir: path.relative(ROOT, mirrorDir).split(path.sep).join('/'),
      syncedAt: new Date().toISOString(),
      hotspotWindowDays: config.hotspotWindowDays ?? 30,
      head: commits[0]
        ? { sha: commits[0].sha, short: commits[0].short, date: commits[0].date, author: commits[0].author, subject: commits[0].subject }
        : null,
      branches: readBranches(mirrorDir),
      hotspots: readHotspots(mirrorDir, branch, config.hotspotWindowDays ?? 30),
      commits,
    };

    writeFileSync(path.join(statePath, 'state.json'), JSON.stringify(state, null, 2) + '\n');
    writeFileSync(path.join(statePath, 'recent-changes.md'), renderChangelog(project, state));
    log.ok(`${project.key} — ${branch} @ ${state.head?.short ?? 'empty'} (${commits.length} commits recorded)`);
    states.push({ project, state });
  }

  writeFileSync(path.join(ROOT, 'project-state', 'SUMMARY.md'), renderSummary(states));
  log.info('\nWrote project-state/SUMMARY.md');
}

main();
